### ISSUE TITLE
No BAM file error

### ISSUE THREAD

**Issue by spencer411** [katholt/RedDog#57]
I'm working with a large data-set of mined data that is bound to have some bad fastq files in it. That being said the pipeline has halted for me several times with the error message below:

"ruffus.ruffus_exceptions.RethrownJobError:

    Exceptions generating parameters for

    'def RedDog.indexBam(...):'

    Original exception:

    Exception #1
    ruffus.ruffus_exceptions.MissingInputFileError(

        No way to run job: Input file ['/network/rit/lab/turnerlab/RedDog_Tutorial/RedDog_output/temp/SRR2339184/SRR2339184.bam'] does not exist):
    for RedDog.indexBam.

    Traceback (most recent call last):
      File "build/bdist.linux-x86_64/egg/ruffus/task.py", line 2279, in parameter_generator
        check_input_files_exist (*param)
      File "build/bdist.linux-x86_64/egg/ruffus/file_name_parameters.py", line 191, in check_input_files_exist
        "Input file ['%s'] does not exist" % f)
    MissingInputFileError:

        No way to run job: Input file ['/network/rit/lab/turnerlab/RedDog_Tutorial/RedDog_output/temp/SRR2339184/SRR2339184.bam'] does not exist"

What I have been doing is just restarting the pipeline each time, which seems to be working, given that the manual says:

"If there is an error during the mapping of reads to create the initial BAM file (including hardware I/O errors that are well beyond the control of the average user), the pipeline will subsequently delete the (empty) BAM and the pipeline will then halt. You should then be able to restart the pipeline."

All this being said, I just want to confirm that by restarting the pipeline, I should be just picking up where I left off, and this will not affect the remaining files running through the process.

Thanks in advance for any help!

**Comment by d-j-e** [comment]
Hmm, forgot some important information... If your reads are about the same size as the rest of your samples, then I'd advise removing that one sample as it could be corrupt somehow (I usually just add a '.f' to the reads so reddog will ignore them).

However, if the read set happens to be larger than the rest of the reads, you might try increasing the walltime and/or memory for the mapping step in the config file (assuming your not running on a local machine) - you may also have to change some of the other steps in the pipe to handle the read set; these are indicated in the config file.  You can also check the log file for that step to see if a helpful error message has been generated...

As to your question about the remaining files; the pipe should pick up where it left off and it will not affect the remaining files running through the process. Let me know how it goes...

**Comment by spencer411** [comment]
Updated the walltime, and removed problem file. Seems to be working fine for now. Thanks!
