### ISSUE TITLE
checkBam failure - no BAM file generated

### ISSUE THREAD

**Issue by illumina-ti** [katholt/RedDog#76]
Hello,

I am trying to run the RedDog pipeline but encountering an error with the .bam file seemingly not being generated to pass the checkBam checkpoint. Error as follows:

(nasp1.1) user: /hdd/FastData0/apps/Reddog-core$ rubra RedDog --config RedDog_config.py --style run

RedDog V1beta.10.3 - phylogeny run

Copyright (c) 2016 David Edwards, Bernie Pope, Kat Holt
All rights reserved. (see README.txt for more details)

Mapping: Bowtie2 V2.2.9
Preset Option: --sensitive-local
1 replicon(s) in FASTA reference AF2122_97_Mbovis
1 replicon(s) to be reported
2 sequence pair(s) to be mapped

Output folder:
/hdd/FastData0/data/reddog_results_bovis_15aug22/

Start Pipeline? (y/n) y

Starting pipeline...
50 jobs to be executed in total
Traceback (most recent call last):
  File "/usr/local/bin/rubra", line 11, in <module>
    load_entry_point('Rubra==0.1.5', 'console_scripts', 'rubra')()
  File "build/bdist.linux-x86_64/egg/rubra/rubra.py", line 66, in main
  File "build/bdist.linux-x86_64/egg/ruffus/task.py", line 2671, in pipeline_run
  File "build/bdist.linux-x86_64/egg/ruffus/task.py", line 2406, in fill_queue_with_job_parameters
  File "build/bdist.linux-x86_64/egg/ruffus/task.py", line 2345, in parameter_generator
ruffus.ruffus_exceptions.RethrownJobError  File "build/bdist.linux-x86_64/egg/ruffus/task.py", line 2345, in parameter_generator
ruffus.ruffus_exceptions.RethrownJobError:

    Exceptions generating parameters for

    'def RedDog.checkBam(...):'

    Original exception:

    Exception #1
    ruffus.ruffus_exceptions.MissingInputFileError(

        No way to run job: Input file ['/hdd/FastData0/data/reddog_results_bovis_15aug22/temp/Bovis-671_S30_L001/Bovis-671_S30_L001.bam'] does not exist):
    for RedDog.checkBam.

    Traceback (most recent call last):
      File "build/bdist.linux-x86_64/egg/ruffus/task.py", line 2279, in parameter_generator
        check_input_files_exist (*param)
      File "build/bdist.linux-x86_64/egg/ruffus/file_name_parameters.py", line 191, in check_input_files_exist
        "Input file ['%s'] does not exist" % f)
    MissingInputFileError:

        No way to run job: Input file ['/hdd/FastData0/data/reddog_results_bovis_15aug22/temp/Bovis-671_S30_L001/Bovis-671_S30_L001.bam'] does not exist

I was wondering if you could provide any advice on how to fix this?

I appreciate all the help.

Cheers,

Ryan.

**Comment by illumina-ti** [comment]
To add to this, I re-ran the pipeline after the checkBam failure and got the following error:

(base) user:/hdd/FastData0/apps/Reddog-core$ rubra RedDog --config RedDog_config --style run

RedDog V1beta.10.3 - phylogeny run

Copyright (c) 2016 David Edwards, Bernie Pope, Kat Holt
All rights reserved. (see README.txt for more details)

Mapping: Bowtie2 V2.2.9
Preset Option: --sensitive-local
1 replicon(s) in FASTA reference AF2122_97_Mbovis
1 replicon(s) to be reported
2 sequence pair(s) to be mapped

Output folder:
/hdd/FastData0/data/reddog_results_bovis_15aug22/

Start Pipeline? (y/n) y

Starting pipeline...
50 jobs to be executed in total
44 jobs left to execute
Error: command failed: python checkBam.py /hdd/FastData0/data/reddog_results_bovis_15aug22/temp/Bovis-671_S30_L001/Bovis-671_S30_L001.bam PE /hdd/FastData0/data/bovis_15aug22/Bovis-671_S30_L001_1.fastq.gz
Error: command failed: python checkBam.py /hdd/FastData0/data/reddog_results_bovis_15aug22/temp/Bovis-672_S31_L001/Bovis-672_S31_L001.bam PE /hdd/FastData0/data/bovis_15aug22/Bovis-672_S31_L001_1.fastq.gz
Error: command failed: sam-stats -A -B /hdd/FastData0/data/reddog_results_bovis_15aug22/temp/Bovis-672_S31_L001/Bovis-672_S31_L001.bam > /hdd/FastData0/data/reddog_results_bovis_15aug22/temp/Bovis-672_S31_L001/Bovis-672_S31_L001_samStats.txt
Error: command failed: sam-stats -A -B /hdd/FastData0/data/reddog_results_bovis_15aug22/temp/Bovis-671_S30_L001/Bovis-671_S30_L001.bam > /hdd/FastData0/data/reddog_results_bovis_15aug22/temp/Bovis-671_S30_L001/Bovis-671_S30_L001_samStats.txt
Traceback (most recent call last):
  File "/usr/local/bin/rubra", line 11, in <module>
    load_entry_point('Rubra==0.1.5', 'console_scripts', 'rubra')()
  File "build/bdist.linux-x86_64/egg/rubra/rubra.py", line 66, in main
  File "build/bdist.linux-x86_64/egg/ruffus/task.py", line 2671, in pipeline_run
  File "build/bdist.linux-x86_64/egg/ruffus/task.py", line 2406, in fill_queue_with_job_parameters
  File "build/bdist.linux-x86_64/egg/ruffus/task.py", line 2345, in parameter_generator
ruffus.ruffus_exceptions.RethrownJobError:

    Exceptions generating parameters for

    'def RedDog.checkpoint_getSamStats(...):'

    Original exception:

    Exception #1
    ruffus.ruffus_exceptions.MissingInputFileError(


        No way to run job: Input file ['/hdd/FastData0/data/reddog_results_bovis_15aug22/temp/success/Bovis-671_S30_L001.getSamStats.Success'] does not exist):
    for RedDog.checkpoint_getSamStats.

    Traceback (most recent call last):
      File "build/bdist.linux-x86_64/egg/ruffus/task.py", line 2279, in parameter_generator
        check_input_files_exist (*param)
      File "build/bdist.linux-x86_64/egg/ruffus/file_name_parameters.py", line 191, in check_input_files_exist
        "Input file ['%s'] does not exist" % f)
    MissingInputFileError:


        No way to run job: Input file ['/hdd/FastData0/data/reddog_results_bovis_15aug22/temp/success/Bovis-671_S30_L001.getSamStats.Success'] does not exist

**Comment by illumina-ti** [comment]
Ended up being a dependency issue with a couple of tools. Now working correctly.
